title = "Upstate Distilling Company"
baseURL = "https://upstatedistilling.com"
tags = ["distillery", "bourbon", "blog",]
languageCode = "en-US"
config = "config.toml"
theme = "upstate-distilling"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    author = "Jewell.Solutions"
    description = "Located in history Saratoga Springs, NY, Upstate Distilling COmpany strives to produce the finest hand-crafted small batch spirits from locally sourced incredients."
    logoBig = "/images/logo-lt.svg"
    logoSmall = "/images/logo-dk.svg"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "upstatedistilling"
    facebook = "upstatedistilling"
    email = "info@upstatedistilling.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Spirits"
    url  = "/#spirits"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 2
[[menu.main]]
    name = "Updates"
    url  = "/#updates"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4